apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mutix
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: graphql-dragontiger
  app.kubernetes.io/name: graphql-dragontiger
  app.kubernetes.io/instance: graphql-dragontiger
